services:
  - type: web
    name: song-summary
    runtime: python
    plan: free
    buildCommand: |
      poetry install
      python manage.py collectstatic --noinput
      python manage.py migrate
      buildCommand: |
        poetry install
        python manage.py collectstatic --noinput
        python manage.py migrate
        python manage.py shell -c "import os; from django.contrib.auth.models import User; \
            User.objects.create_superuser(os.getenv('ADMIN_USERNAME'), os.getenv('ADMIN_EMAIL'), os.getenv('ADMIN_PASSWORD')) \
            if not User.objects.filter(username=os.getenv('ADMIN_USERNAME')).exists() else print('Superuser already exists')"
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        value: adminpassword