# Generated by Django 5.1.3 on 2024-11-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=255)),
                ('song_title', models.CharField(max_length=255)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('countries', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
